### PR TITLE
Replace local Spotify API with web based API

### PR DESCRIPTION
**Pull request by MeikelLP**
Due to the latest errors caused by Spotify removing the local API the Spotify part of this application did not work anymore (see #299).
To provide a future-proof solution I implemented the [Spotify API for .NET](https://github.com/JohnnyCrazy/SpotifyAPI-NET/) which is also listed in the [spotify libaries](https://developer.spotify.com/documentation/web-api/libraries/).

I also shortened the code drastically due multiple code parts are not required anymore.

If you have any questions like "how" / "why" ... just ask.

***WARNING***
* To implement this library I was required to remove the applications signing (`.snk` files and references). Which caused the library to be **not included** (I don't know why exactly).
* Using this library requires the user to authenticate via a browser. It also opens everytime you start the app saying "Auth successful". This is currently not fixable (my knowledge).

### CODE REVIEW

**Comment by dlrudie** [comment]
I like the idea of this just due to the fact Snip wouldn't require elevated privileges. I'll have to review this thoroughly.

**Comment by markspolakovs** [comment]
Hmm - doesn't the spotify API library store the OAuth refresh token somewhere on the system? That wouldn't cause the "success" popup as long as the session is valid. If it isn't, it isn't doing its job properly.

**Comment by MeikelLP** [comment]
@dlrudie 
 
1. I'm not using any LINQ in my code so far.
2. I can see that. I'm adding it again.

For the web server topic: SpotifyAPI-NET has a "simple" HTTP server for this purpose self-implemented running under localhost and catches the callback. The library also opens the browser automatically. At this point, I don't know whether you can configure this behavior.

**Comment by dlrudie** [comment]
In commit a041c54

Line 21 of Spotify.cs adds linq.
Line 143 uses linq to join strings.

**Comment by MeikelLP** [comment]
Oh, you are right.
At this point I won't tell you why should use LINQ, you can google that yourself. 
As a professional C# developer I can assure you that LINQ is nothing bad. Even (if you don't use LINQ2SQL or EntityFramework) it brings performance improvements. Ever modern language today uses lambda expressions to improve development speed. Even java did it finally with Java 8.

**Comment by dlrudie** [comment]
Oh, I know its benefits. I just don't like the way it looks and integrates with existing code. It just looks funky to me to have a bunch of SQL-like code in the middle of other code. Plus if I started to implement LINQ then I'd want to re-write Snip from the ground up to take advantage of it. But currently Snip isn't exactly a heavy-duty application that needs a lot of performance. :)

**Comment by MeikelLP** [comment]
I don't want to implement LINQ projects wide. I'm just used to use LINQ in as utilies (like here selecting online the name from a list of objects). And it's a simple lambda method nothing fancy like `from trackInformation.Item.Artists artist select artist.name` which would do the exact same thing as `trackInformation.Item.Artists.Select(x => x.Name)`.

**Comment by dlrudie** [comment]
I'm down for it. I don't mind.

Really the whole reason 99% of my programs exist is that I develop them originally for myself for my own need, and then release them to the public because why not. Then everyone wants features for this, and features for that, and all kinds of things that my program was originally never designed to have, and then things get messy and ugly. ;)

Now that it's gained in usage and popularity it could definitely use a lot of polish.

**Comment by EpikYummeh** [comment]
Any update on merging this PR?

**Comment by MeikelLP** [comment]
@dlrudie ?

**Comment by dlrudie** [comment]
Sorry. Been super busy with work. (80+ hour work-weeks make me not want to come home and touch the computer). I'm trying to get caught up this weekend though. I'll review this again.

I'm actually surprised my implementation is still working perfectly fine with all the updates they've made to the Spotify client. I do want to get away from my implementation though due to needing elevated privileges.

**Pull request closed without merging**
