### PR TITLE
VS project handling. NL translation

### PR DESCRIPTION
**Pull request by Eegee**
Hello dlrudie,
I've changed Snip a bit so that it doesn't write lots of times to the files every second, by remembering the text value and only write if the current value is different.
Also, I've adjusted the project file and cmd file to support spaces in the project path and I've updated the Dutch translation.
Could you please review it and perhaps integrate it back into your master?
Thanks,
Erik Jan

### CODE REVIEW

**Comment by dlrudie** [comment]
Snip never wrote to the file every second anyway.  It scanned the title itself and compared it to the previous title.  It only writes to the text file if it's different.

Updated request to exclude the TextHandler.cs changes and I'll merge it.

Thanks for the support.

**Comment by Eegee** [comment]
Sorry for the wait, I finally got around to it. It's also because I'm kinda newb with Github...

I just wanted to do a quick check again why I saw superfluous file writing on my PC in February, but I can't reproduce it anymore. Don't know what happened then. And you're right, Snip already did a comparison; my bad. So I removed my changes in TextHandler.cs as per your suggestion.
it's now only the translations to Dutch and the VS project supporting spaces in the project path.

**Comment by dlrudie** [comment]
I noticed some of the NL strings are reverted to their English counterpart. Is this intentional?

**Comment by dlrudie** [comment]
Can you please create a separate pull request just for the NL translation update, and one for the path with spaces update? Thank you.

**Comment by Eegee** [comment]
David Rudie wrote:
> I noticed some of the NL strings are reverted to their English
> counterpart. Is this intentional?

Actually, no, I did not revert to any English text.
I only updated Dutch strings.

> Can you please create a separate pull request just for the NL
> translation update, ...

OK, I've just created a pull request for the NL translation update only.
I'll do the one on path and spaces later.

EJ

**Pull request closed without merging**
