### PR TITLE
Hotfix for broken iTunes events

### LINKED ISSUE #202: Error HRESULT E_FAIL with iTunes
I updated to the latest version of iTunes for Windows 10 (version 12.7.0.166), but since doing so it doesn't seem to want to play nicely with Snip (version 6.9.1). Whenever I open Snip, it opens iTunes as well, but immediately after iTunes opens I get the following error:

_Please exit iTunes and reselect iTunes from within Snip.

Error HRESULT E_FAIL has been returned from a call to a COM component._ 

iTunes seems to function fine, but Snip is unable to pick up song info from iTunes. I've tried closing and selecting Snip->iTunes to re-launch iTunes as instructed in the error message, but the same error comes up each time. I've experimented with setting Snip to another service (Spotify, VLC, etc.), opening iTunes separately, and then setting it back to iTunes, and I've also uninstalled and re-installed, but despite my best efforts the error message comes up each time. Has anyone else seen this kind of thing before?

### LINKED ISSUE #205: Having problems with the new iTunes in Windows
Every time I select it, it tells me to please exit iTunes and reselect iTunes from within Snip. But when I do it gives the same error:

Error: HRESULT E_FAIL has been returned from a call to a COM component.

### LINKED ISSUE #208: Error upon launch of Snip
Nasty dialog appears when Snip is started:

Please exit iTunes and reelect iTunes from within Snip.
Error HRESULT E_FAIL has been returned from call to a COM component.

It doesn't make any difference if I follow this instruction or not. No text from currently playing iTunes music ever shows.

I change over to Spotify and all works.

Back to iTunes and this error appears again.

Snip v6.9.1
iTunes v12.7.0.166

capture

### LINKED ISSUE #211: Doesn't Work With iTunes
I keep getting interface not supported. can you please update to work with iTunes.

### LINKED ISSUE #213: Still incompatible with Itunes 12.7
10.22.2017

Still incompatible with itunes 12.7 or above.

### LINKED ISSUE #214: Itunes not working with Snip
I know this has been posted a lot with text file not reading with Itunes. Was just wondering if there's a timetable on an update to fix it. thanks for the great free program has worked great until the latest Itunes update.

### LINKED ISSUE #221: iTunes error - "Error HRESULT E_FAIL has been returned from a call to a COM component"
Hi,

iTunes has recently had an update and now snip is not working with it. I tried redownloading snip but it has come up with the same error. Screenshot below.

image

Thank you for your work with Snip. Please could you fix this when possible <3

### LINKED ISSUE #223: iTunes integration not working
Hello!
Wonderful little piece of software, except I can't get it to do what I want it to, because:
- When I first ran it, I had iTunes open. When I right clicked it in the tray and selected iTunes, I got an error asking me to close iTunes and then re-select it from the menu. Under this, there's also two sentences that say "No such interface supported".
- Ok so I did it, but no luck: "no such interface supported" error. Again.

What now? Help!
Thanks in advance.

### LINKED ISSUE #236: Snip not working correctly with ITunes
I'm a beginning streamer putting music from itunes onto my steam, but when i open Itunes through snip i get this error message
capture
All of the music has been downloaded through apple music, but i get this message when itunes starts up through Snip.

### PR DESCRIPTION
**Pull request by markspolakovs**
Apple seem to have broken their own COM events. To get iTunes back to working, this commit now makes the iTunes interface poll the current track as part of the Update() cycle.

Fixes #202, fixes #205, fixes #208, fixes #211, fixes #213, fixes #214, fixes #221, fixes #223, fixes #236 (wow).

### CODE REVIEW

**Comment by MackKnife** [comment]
cant wait till its implented !

**Comment by markspolakovs** [comment]
I have a build of this hotfix up at https://github.com/markspolakovs/Snip/releases/tag/v6.9.1-hotfix.1 - keep in mind though that this is unsupported and unverified.

**Comment by MackKnife** [comment]
i can tell ya its working for me  !  Thanks

**Comment by MackKnife** [comment]
i noticed a bug  in that:  Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.Runtime.InteropServices.COMException (0x8000FFFF): Schwerwiegender Fehler (Ausnahme von HRESULT: 0x8000FFFF (E_UNEXPECTED))
   bei iTunesLib.IITArtwork.SaveArtworkToFile(String filePath)
   bei Winter.iTunes.Update() in C:\Code\Snip\Snip\Players\iTunes.cs:Zeile 92.
   bei Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e) in C:\Code\Snip\Snip\Snip.cs:Zeile 505.
   bei System.Windows.Forms.Timer.OnTick(EventArgs e)
   bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2600.0 built by: NET471REL1LAST.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
Snip
    Assembly-Version: 6.9.1.0.
    Win32-Version: 6.9.1.0.
    CodeBase: file:///C:/Users/Jens/Downloads/Snip/Snip.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2600.0 built by: NET471REL1LAST.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Microsoft.CSharp
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.7.2600.0 built by: NET471REL1LAST.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
----------------------------------------
System.Dynamic
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
----------------------------------------
Microsoft.CSharp.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_de_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by dlrudie** [comment]
Apple fixed this themselves. Thanks for the support though! I always appreciate it.

**Pull request closed without merging**
