### PR TITLE
count whats added to the string after truncation

### PR DESCRIPTION
**Pull request by kamijoutouma**
If you add a space and 3 dots after limiting it to 128 the result will be 132 so instead limit to 125 to add these without crashing the application.
Fixes Issue https://github.com/dlrudie/Snip/issues/67

### CODE REVIEW

**Comment by kamijoutouma** [comment]
After doing some testing i determined that 126 is better to avoid cutting off at 125 it also no longer crashes now with 126 so :D

**Comment by kamijoutouma** [comment]
@dlrudie o.o

**Comment by dlrudie** [comment]
This was an oversight.  Thanks.

**Comment by kamijoutouma** [comment]
np xD

**Pull request merged**
